services:
  - type: web
    name: imagemaster-pro
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: U2NET_HOME
        value: /opt/render/.u2net
